export const SAVE_NEW_TASK = 'SAVE_NEW_TASK';
export const FETCH_ALL_TASKS = 'FETCH_ALL_TASKS';
export const FETCH_ALL_TASKS_SUCCESS = 'FETCH_ALL_TASKS_SUCCESS';
export const FETCH_ALL_TASKS_FAIL = 'FETCH_ALL_TASKS_FAIL';
export const DELETE_TASKS = 'DELETE_TASKS';
export const EDIT_TASKS = 'EDIT_TASKS';
export const TABLE_ROW_CLICKED = 'TABLE_ROW_CLICKED';
export const MODAL_STATE_CHANGED = 'MODAL_STATE_CHANGED';